neurosnap/neovimcraft

- src/lib/resources.json
A minimal preconfigured neovim setup written in lua.
> Update: added nii-nvim to resources.json

- src/lib/resources.json
https://github.com/mattleong/CosmicNvim
Thanks! 🙏
> Add CosmicNvim to resources

- src/lib/nav.svelte
- src/lib/plugin-view.svelte
- src/lib/plugin.svelte
- src/routes/about.svelte
- src/routes/guides.svelte
- src/routes/plugin/[username]/[repo].svelte
> Remove target attributes from all links

- src/lib/manual.json
I ran into the same issue as #23, so I manually added an entry.
> Added zenburn.nvim, a low contrast color scheme

- src/lib/manual.json
> add mrjones2014/smart-splits.nvim

- src/lib/manual.json
Add a plugin for auto-previewing LaTeX and markdown and other files.
> Add "frabjous/knap" to manual.json

- src/lib/manual.json
This is a plugin I wrote implementing Readline shortcuts in Neovim.
https://github.com/linty-org/readline.nvim
> Add `readline.nvim`

- src/lib/manual.json
Hey Eric,
Really like the site you created, with the pr I would like to add my plugins to your site.
Have a great day and thank you if you press merge, I really appreciate it.
Koen
> Add `minimal-tabline.nvim`, `peepsight.nvim`, and `cmd-palette.nvim`

- src/lib/manual.json
Hey Eric,
I would like to add my statusline to your site.
Thanks!
> add strash/everybody-wants-that-line.nvim

- src/lib/manual.json
Hello o/
I would like to add my plugin to your website =)
> Add brenoprata10/nvim-highlight-colors plugin

- src/lib/manual.json
Hi, PR to add my first Neovim plugin `overlength.nvim` : a small Lua plugin to highlight too long lines.
> Add lcheylus/overlength.nvim

- src/lib/manual.json
Add a plugin to listen to music in neovim using mpv
> Add Saverio976/music.nvim

- src/lib/manual.json
Hello
Is it possible to add this plugin to your site please ?
Cheers
> Add TimotheeSai/git-sessions.nvim

- .github/workflows/deploy.yml
- Makefile
- data/manual.json
- data/resources.json
- src/entities.ts
- src/github.ts
- src/scripts/html.ts
- src/scripts/process.ts
- src/scripts/resource.ts
- src/scripts/static.ts
- src/stht.ts
- src/types.ts
Closes: https://github.com/neurosnap/neovimcraft/issues/175
> srht codeforge support

- data/manual.json
Thanks for the great website and curated list!
The changes have been generated from the `make resource` script.
> add `shortcuts/no-neck-pain.nvim`

- data/manual.json
> Add projectmgr.nvim to neovimcraft

- data/manual.json
https://github.com/chrisgrieser/nvim-spider
> add new plugin: nvim-spider

- data/manual.json
added [gist.nvim](https://github.com/rawnly/gist.nvim)
> feat: added gist.nvim

- data/manual.json
> Add decipher.nvim

- data/resources-config.json
close https://github.com/neurosnap/neovimcraft/pull/296
> add spacevim

- data/manual.json
> Add `adigitoleo/overview.nvim`
